### ISSUE TITLE
Clock setup - better documentation/API?

### ISSUE THREAD

**Issue by pferreir** [samcrow/stm32_i2s#1]
I'm trying to connect an STM32F411 to a WM8731 codec in (codec) slave mode. According to the datasheet of the codec, MCLK should be receiving a pulse at 12.288MHz. I have set it up to an 8 KHz sample rate.
I may be misinterpreting the API, but it's not clear to me how to interpret the `frequency_in` parameter in [`MasterConfig::with_sample_rate(...)`](https://docs.rs/stm32_i2s_v12x/0.2.0/stm32_i2s_v12x/struct.MasterConfig.html#impl). I assume that would be the 12.288MHz in this case? And from what I see the lib doesn't automatically set the PLL to do that? Your examples use 38.4 MHz, which I don't know where it comes from.

**Comment by samcrow** [comment]
That part of the API is not very easy to use. I set it up like that because different microcontrollers have different ways of generating the clocks that go to the SPI/I2S peripherals. Even within the STM32F4 series, some models can send different frequencies to different I2S peripherals, while others (like the F411) have only one I2S clock that goes to all the I2S peripherals.

To keep this library usable on a wide range of microcontrollers, PLLs and other setup outside the I2S peripherals are out of scope.

For the F411, the `frequency_in` value should match the frequency produced by the PLLI2S (or from I2S_CKIN, if that is selected as the I2S clock source). If you are using `stm32f4xx-hal`, this is ideally the same as the frequency passed to [the i2s_clk configuration function](https://docs.rs/stm32f4xx-hal/0.10.1/stm32f4xx_hal/rcc/struct.CFGR.html#method.i2s_clk).

The `MasterConfig::with_sample_rate` function configures the clock divider in the I2S peripheral to get as close as possible to the requested sample rate using the `frequency_in` value.

There is [a more detailed example here](https://github.com/stm32-rs/stm32f4xx-hal/blob/master/examples/i2s-audio-out.rs). That example runs on an STM32F411 and produces a 12.288 MHz master clock output.

In line 101 of the example, it asks for an 86 MHz clock from the PLLI2S into the I2S peripherals. The same 86 MHz value gets passed to `MasterConfig::with_sample_rate` in line 137. The I2S peripheral divides that by 7 to get approximately 12.288 Mhz, which goes directly to the master clock output.

Because the master clock is always 256 times the sample rate with this I2S peripheral, the sample rate must be 48 kHz. If you ask for a sample rate of 8 kHz, the master clock will be only 2.048 MHz.

I hope that helps with your specific situation. More generally, I don't have a good idea for how to make this part of the API better but I'd welcome suggestions.

**Comment by YruamaLairba** [comment]
I close this, clock setup is greatly improved in 0.3
Edit: lol, i'm stupid, only issue opener and repo owner can close issue

**Comment by samcrow** [comment]
Thanks for the update, closing.
